[platformio]
default_envs = native


[env:native]
platform = native
build_type = debug

build_flags =
    -I.
    -Icore
    -Isystem
    -Icommunication
    -Ilib

build_src_filter =
    +<*>
    +<../core/*>
    +<../system/*>
    +<../communication/*>